### ISSUE TITLE
Compiled release of the plugin

### ISSUE THREAD

**Issue by wk-952** [codecat/ClawSearch#4]
Hello, first I would like to point out that this is not a bug report, but rather a request.
For quite some time I've wanted to use your plugin, but I don't have VS2015 and compiling it on VS2013 is painful, throws many linking issues as in issue #3 .

Could you please release a compiled package of the plugin occasionally ?

**Comment by codecat** [comment]
Sure, I'll take a look late tonight.

**Comment by codecat** [comment]
Hey, I've uploaded prebuilt binaries [here](https://github.com/codecat/ClawSearch/releases). Let me know if they work, I haven't had much time to try it yet today.

I've also fixed a few building errors and committed those, so if you want to compile it yourself, maybe it will work now.

**Comment by wk-952** [comment]
Thanks a lot, the 32-bit version worked, but the 64-bit version didn't, log tab says failed to load plugin.

As for compiling the project, i found that the linking problem was because of the libraries `IUP` and `CD` since they're built with `static` linking to `Visual C++ 14.0 (2015)` as stated here in the [download tips page](http://webserver2.tecgraf.puc-rio.br/cd/en/download_tips.html).
After replacing all `.lib` files of `IUP` and `CD` with the ones built for `Visual C++ 12.0 (2013)` , the project was successfully compiled!

But comes another problem, if the plugin was compiled with the `static` version of both libraries, then the 64-bit version fails to be loaded in the debugger, but if the project was built with the `dynamic` version of the libraries then it works! but of course you have to copy/paste the `.dll` files along the with the `.dp64` file.

**Comment by codecat** [comment]
That's interesting. I don't really understand why that would be a problem. Maybe it's linking with the wrong static lib files or something?

Since this issue is solved, I'll close it now. Perhaps open a new issue for the static libs?

**Comment by wk-952** [comment]
Sure, will do, i'll try to figure out what's wrong (if i could) before opening a new issue.
